### ISSUE TITLE
divvun-checker --json not documented by --help

### ISSUE THREAD

**Issue by snomos** [divvun/libdivvun#38]
`divvun-checker --help` gives a.o. the following:

```
  -z, --null-flush     (Ignored, we always flush on <STREAMCMD:FLUSH>,
                       outputting \0 if --json).
```

but `--json` is not mentioned or documented anywhere in the `--help` output. Could there be other options that are not documented?

**Comment by unhammer** [comment]
`--json` is an argument of divvun-suggest, not divvun-checker. 

The help output is generated directly from the options array, so it should be complete.

But I agree it's confusing that checker mentions a suggest-option, I'll reword that.
