### ISSUE TITLE
refer to form of *suggestion* in errors.xml

### ISSUE THREAD

**Issue by unhammer** [divvun/libdivvun#40]
There is currently no way to refer to a (dynamically generated) suggestion in errors.xml messages. We have $1 for the current form, $2 (and $3 etc.) for context words marked using `ADDRELATION ($2)`, but we can't yet refer to the `&SUGGEST`-ed form.

There may be several suggested forms, but for now we can have a feature that just picks an arbitrary one.

**Comment by snomos** [comment]
I suggest `$0` to always return the first suggestion.

**Comment by unhammer** [comment]
I think that would make it a bit confusing that $1 does not refer to the second suggestion, but to the input word form …
