### ISSUE TITLE
divvun-checker --spec <spec> --variant <variant> crashes

### ISSUE THREAD

**Issue by albbas** [divvun/libdivvun#41]
On Linux this is the result of the command
```
❯ divvun-checker --spec tools/grammarcheckers/pipespec.xml --variant smegramrelease
terminate called after throwing an instance of 'TransducerHeaderException'
Aborted
```
divvun-checker also crashes on macOS when using these options.

**Comment by albbas** [comment]
When running the command in the directory where pipeline.xml is, then the command succeeds. It seems that the paths to the .hfst files are miscalculated.

**Comment by unhammer** [comment]
Aha, we're probably looking in CWD for a relative path, should prepend `tools/grammarcheckers/` in your example.
