### ISSUE TITLE
withCasing() must return or throw

### ISSUE THREAD

**Issue by TinoDidriksen** [divvun/libdivvun#45]
````
I: Program returns random data in a function
E: libdivvun no-return-in-nonvoid-function suggest.hpp:158
````

Function withCasing() on https://github.com/divvun/libdivvun/blob/master/src/suggest.hpp#L144 must do something at the end. If it's never supposed to reach that, throw a dummy exception - even just `throw 1` will do.

**Comment by unhammer** [comment]
Committed, though should it be possible to reach the end when compiled with `-Werror=switch`?
