### ISSUE TITLE
malloc(): invalid size (unsorted) in gcc-10

### ISSUE THREAD

**Issue by unhammer** [divvun/libdivvun#49]
```
export CC=gcc-10
./configure 
make clean
make 
make check
```
```
divvun-checker: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
./run: line 23: 2013050 Aborted                 (core dumped) ../../src/divvun-checker "${args[@]}" < input."$n".txt > output."$n".json
FAIL run.xml (exit status: 134)
```

**Comment by unhammer** [comment]
Argh this has been there since 6f7962ee32a77936bb5a266701a22f03042b8642 – as far back as we can compile without getting older dependencies

**Comment by unhammer** [comment]
I don't get it with tcmalloc

**Comment by flammie** [comment]
I don't get this with GCC 10 on gentoo:
```
cc --version
gcc (Gentoo 10.3.0-r2 p3) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt KEINE Garantie; auch nicht für MARKTGÄNGIGKEIT oder FÜR SPEZIELLE ZWECKE.
```
... but I'm not sure of tcmalloc, it doesn't show up in configure?

**Comment by unhammer** [comment]
I often run with `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4` which makes some things faster, makes other things break, and makes yet other things confusingly not break.

**Comment by unhammer** [comment]
Seems like it's in hfst-pmatch, simply doing

	hfst_ol::PmatchContainer * t = new hfst_ol::PmatchContainer(instream);

triggers it

**Comment by flammie** [comment]
Ah yeah I get it after update of hfst now.
[Valground log data](https://github.com/divvun/libdivvun/files/7677005/valgrind-log.txt)

**Comment by flammie** [comment]
So it's a regression between 3.15.5 and now, this includes: the c++ modernisation stuff, decoupling  of foma and openfst and few bug fixes plus lastly some new things in tokenise and pmatch... it doesn't show up in the basic pmatch-functionality-test even with valgrind so there must be some other condition to it too (hfst-pmatch does `hfst_ol::PmatchContainer container(instream);` in beginning of `main`)..

**Comment by unhammer** [comment]
https://github.com/hfst/hfst/commit/1af6a1026e4890c9fc27e4b75d1844c706ac272e not 100% sure I'm testing the same thing

**Comment by unhammer** [comment]
the test in hfst works fine if I include config.h, specifically this line:
`#define USE_ICU_UNICODE 1
`

**Comment by unhammer** [comment]
So if I configure libdivvun with 

```
./configure   CFLAGS="-DUSE_ICU_UNICODE=1" CXXFLAGS="-DUSE_ICU_UNICODE=1"
```

it works fine in gcc-10 with regular malloc. But shouldn't that flag only be checked at compile time? (My hfst is compiled with icu.)

**Comment by TinoDidriksen** [comment]
Fixed in https://github.com/hfst/hfst/commit/cea87758b2ca54eba63ebcdbbaad3403f5e4ff30
