### ISSUE TITLE
clang-format

### ISSUE THREAD

**Issue by flammie** [divvun/libdivvun#55]
I think we should just clang-format hte code and add .clang-format and be done with it. I put https://github.com/hfst/hfst/blob/master/.clang-format in HFST earlier and https://github.com/apertium/lttoolbox/pull/143 for is apertium's discussion of that but if there's something that fits to existing style better it'd be good too.

**Comment by snomos** [comment]
Sounds good, please do. @unhammer do you have viewpoints?

**Comment by unhammer** [comment]
Sounds good to me.

It seems I've used tabs, probably to keep things fairly close to CG-3 (which uses https://github.com/GrammarSoft/cg3/blob/main/.clang-format ). If we choose a format that's fairly close to what the code already has, that would make it easier to compare git region diffs. But apart from that I don't really care about the individual .clang-format settings.
