### ISSUE TITLE
divvun-checker crashes on specific input

### ISSUE THREAD

**Issue by albbas** [divvun/libdivvun#57]
`echo Markens Grø d Markens” j ¶|divvun-checker -a smj.zcheck` causes a crash.

The result on an Intel Mac is: 
```
{"errs":[["Grø",8,11,"typo","Báhko \"Grø\" vuojnnu boasstot tjáleduvvam.",["Gro","Ärø","Årø","Ærø","Gry","Grøa"],"\"Grø\" vuojnnu boasstot tjáleduvvam"],["Markens",14,21,"typo","Báhko \"Markens\" vuojnnu boasstot tjáleduvvam.",["Marken","Martens","Markena","Markenis","Márens","Markajs","Markas","Markan","Mareno","Maiken"],"\"Markens\" vuojnnu boasstot tjáleduvvam"]],"text":"Markens Grø d Markens” j ¶"}
divvun-checker(73526,0x7ff854213680) malloc: *** error for object 0x60000af25ca0: pointer being freed was not allocated
divvun-checker(73526,0x7ff854213680) malloc: *** set a breakpoint in malloc_error_break to debug
```

divvun-checker --version: 0.3.10
smj.zcheck is a few days old build of the grammarchecker

**Comment by albbas** [comment]
The result on Ubuntu Linux is:
```
{"errs":[["Grø",8,11,"typo","Báhko \"Grø\" vuojnnu boasstot tjáleduvvam.",["Gro","Gry","Grøa","Ärø","Årø","Ærø"],"\"Grø\" vuojnnu boasstot tjáleduvvam"],["Markens",14,21,"typo","Báhko \"Markens\" vuojnnu boasstot tjáleduvvam.",["Marken","Markena","Markenis","Martens","Márens","Markajs","Markan","Markas","Mareno","Malkenes"],"\"Markens\" vuojnnu boasstot tjáleduvvam"]],"text":"Markens Grø d Markens” j ¶"}
double free or corruption (!prev)
Aborted
```

**Comment by albbas** [comment]
Another sentence, different error message:

echo Sámegiela båhti ienep vuojnnusij almulasjvuodan, nav dagu rahtegalbajn moadda sáme guovlojn. Boahttejage máhttep ihkap vat mannagoahtet ienebut, ja de bessap vuojnnet sáme galbajt rijkarájájn ja girddesaljojn nuorttan, ja ådå pássajn jali ID-kårtåjn sjaddá aj sáme tæksta. Sámegiella vuojttá ådå arienájt, Giellavahko oattjoj Lemet Máhtte Eira Sara Giellalåpptim-bálkáv jårggålimes Minecraft Sámegiellaj. Dálla galggi nuora oahppa háledit dråvnåj – sámegiellaj! ¶ | divvun-checker -a smj.zcheck

```
munmap_chunk(): invalid pointer
Aborted
```

**Comment by unhammer** [comment]
@TinoDidriksen @mr-martian maybe related to last week's changes?

**Comment by TinoDidriksen** [comment]
Nightly packages are now built with the workaround. Valgrind has no complaints.

No clue what object is held in multiple places to cause the double free, but these types are now insulated from being freed twice.
