### ISSUE TITLE
Show multiword-suggestions and underlines in divvun-suggest (non-json)

### ISSUE THREAD

**Issue by unhammer** [divvun/libdivvun#62]
Suggestions that are "together" will have the same colour, if the next word is not LINK'd to the previous one then we use a different colour. 

So where we now have
```
"<foo>"
  "foo" tags
fixfoo+Tag fixed
"<bar>"
  "bar" tags
fixbar+Tag barfixed
```

we would want
```
"<foo>"
  "foo" tags
GREEN fixfoo+Tag fixed
"<bar>"
  "bar" tags
GREEN fixbar+Tag barfixed
```
if the words are in one underline (eg. &LINK), but
```
"<foo>"
  "foo" tags
GREEN fixfoo+Tag fixed
"<bar>"
  "bar" tags
RED fixbar+Tag barfixed
```

if they're separate. So the "default" is that colours just alternate green/red

**Comment by albbas** [comment]
Testene går etter indeksene som divvun-checker gir. Om dette betyr at indeksene endres, må vi gjøre endringer i .yaml-testene også.

**Comment by unhammer** [comment]
Køyrer du testar på json output? (Her var det snakk om å endra ikkje-json-formatet.)

**Comment by albbas** [comment]
Ja, lager json av yaml-setningene som lar seg sammenligne med divvun-checker sitt output.

**Comment by unhammer** [comment]
![image](https://github.com/divvun/libdivvun/assets/56868/bd7b9200-dcd0-4963-bf19-e4184bc71372)


Ser ↑ OK ut?

Alternativt går det òg an å få med nøyaktig det som blir sendt til pluginen, men då er det ikkje lenger kopla til readings, så det me må skriva det på kohort-nivå:

![image](https://github.com/divvun/libdivvun/assets/56868/f7432c73-4414-4023-8955-ba9b7faf2230)

eller det går til og med an å visa begge:

![image](https://github.com/divvun/libdivvun/assets/56868/ad7cd918-2d1e-44a6-b46f-d38407f876ed)

**Comment by unhammer** [comment]
![image](https://github.com/divvun/libdivvun/assets/56868/ba2b1b01-ce88-46d3-b361-9a6a3f5ffadb)
end result
