### ISSUE TITLE
 Include all possibilities if several possible &SUGGEST's (on either side of the relation)

### ISSUE THREAD

**Issue by unhammer** [divvun/libdivvun#63]
cf. https://github.com/divvun/libdivvun/issues/61
and https://github.com/divvun/libdivvun/blob/4629a43a52b0f46257ac84b2ed4f72d83a185ee4/src/suggest.cpp#L438-L440
we only include the arbitrarily first suggested form when combining suggestions from two words, e.g. if input was 

```
"<ta>"
	"ta" V Inf <W:0> @V &syn-phrasal-verb ID:1
	"spille" V Inf <W:0> @V &syn-phrasal-verb &SUGGEST ID:1 R:RIGHT:2
: 
"<opp>"
	"opp" Adv <W:0> @Adv &syn-phrasal-verb ID:2 &COERROR
	"inn" Adv <W:0> @Adv &syn-phrasal-verb &SUGGEST ID:2 &COERROR
	"inn!" Adv <W:0> @Adv &syn-phrasal-verb &SUGGEST ID:2 &COERROR
```
we should get both "spille inn" and "spille inn!" but we currently just get one of them. 

Similarly if there are several suggestions on the non-COERROR cohort.

**Comment by unhammer** [comment]
This actually works if you use the error tag to signify what goes together:
```

"<ta>"
	"ta" V Inf <W:0> @V &syn-phrasal-verb ID:2
	"spille" V Inf <W:0> @V &syn-phrasal-verb &SUGGEST ID:2 R:RIGHT:4
	"lage" V Inf <W:0> @V &syn-phrasal-verb1 &SUGGEST ID:2 R:RIGHT:4
: 
"<opp>"
	"opp" Adv <W:0> @Adv ID:4 &COERROR
	"inn" Adv <W:0> @Adv &syn-phrasal-verb &SUGGEST ID:4 &COERROR
	"opptak" Adv <W:0> @Adv &syn-phrasal-verb1 &SUGGEST ID:4 &COERROR
: 
: 
```

![image](https://github.com/divvun/libdivvun/assets/56868/9fbc672d-8153-4350-bb3b-88b84654c311)

**Comment by unhammer** [comment]
what doesn't yet work is getting the cross product of all combinations which use the same error tag  – but do we need/want that?

**Comment by snomos** [comment]
Not sure, would need more examples to prove the need.
