### ISSUE TITLE
don't always change case when moving

### ISSUE THREAD

**Issue by unhammer** [divvun/libdivvun#79]
i det her tilfellet så må vi ikkje forandre til storbokstav:
```
"<Eoraip>"              an Eoraip       →  na HEorpa
        "Eoraip" Prop Noun Fem Com Sg <W:0.0> &msyn-gen-case-nouns ID:10 R:$2:9 R:LEFT:9 ADD:863:msyn-gen-case-nouns COPY:864:msyn-gen-case-nouns ADDRELATION($2):888
msyn-gen-case-nouns
        "Eoraip" Prop Noun Fem <W:0.0> Gen Sg DefArt SUGGEST SUGGEST ID:10 R:$2:9 R:LEFT:9 ADD:863:msyn-gen-case-nouns COPY:864:msyn-gen-case-nouns MAP:891:LOCK_READING
Eoraip+Prop+Noun+Fem+Gen+Sg+DefArt      hEorpa
;       "Eoraip" Prop Noun Fem Com Sg Len <W:0.0> REMOVE:2185
;       "Eoraip" Prop Noun Fem Voc Sg <W:0.0> REMOVE:1362
"<.>"
        "." Punct Fin <W:0.0>
```

dvs. me vil endra 

- … an Eoraip …
til
- … an hEorpa …

midt i setning, ikkje _*an HEorpa_ (spørsmål: kva skjer med _hEorpa_ i starten av ei setning på irsk? eller vil du alltid ha _na_ føre det slik at det ikkje skjer i praksis?)

could maybe only uppercase things moving left and lowercase things moving right, or rules could `fixedcase` the propers

**Comment by unhammer** [comment]
@snomos er det vanskeleg teknisk å gjera at alle Prop i gramcheck-analysatoren får ein ny tagg `<fixedcase>`? Linda meinte det var ein betre plass å ha det enn i CG.

**Comment by snomos** [comment]
@unhammer eg føreslår at det blir gjort i ei tidleg CG-fil heller enn i analysatoren. I ein fst er det redundant (implisitt i `Prop`), og vil berre gjera fst-en større utan å tilføra noko. Og taggen skal truleg leggjast til fleire stader i lexc-koden.

I ei CG-fil er det éin regel (og truleg ein triviell ein), og så er saka klar.
